<?php

/**
 * PluginaPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPage');
    }
}